language: julia
julia:
     - 1.6
#    - release
#    - nightly
os:
    - linux
    - osx

after_success:
    - julia -e 'cd(Pkg.dir("FinNetValu")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
#coveralls: true
codecov: true
matrix:
fast_finish: true
